# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/andre/Documents/Processor/SOC_GR0040/SOC_GR0040_REFACTOR/SOC_GR0040_REFACTOR.srcs/sources_1/ip/ROM_8_512_H/ROM_8_512_H.xci
# IP: The module: 'ROM_8_512_H' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/andre/Documents/Processor/SOC_GR0040/SOC_GR0040_REFACTOR/SOC_GR0040_REFACTOR.gen/sources_1/ip/ROM_8_512_H/ROM_8_512_H_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_8_512_H'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/andre/Documents/Processor/SOC_GR0040/SOC_GR0040_REFACTOR/SOC_GR0040_REFACTOR.srcs/sources_1/ip/ROM_8_512_H/ROM_8_512_H.xci
# IP: The module: 'ROM_8_512_H' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/andre/Documents/Processor/SOC_GR0040/SOC_GR0040_REFACTOR/SOC_GR0040_REFACTOR.gen/sources_1/ip/ROM_8_512_H/ROM_8_512_H_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_8_512_H'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
