set_property IOSTANDARD LVCMOS33 [get_ports i_clk]
set_property IOSTANDARD LVCMOS33 [get_ports i_rst]
set_property PACKAGE_PIN K17 [get_ports i_clk]

set_property IOSTANDARD LVCMOS33 [get_ports {i_par_i[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_par_i[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_par_i[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_par_i[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_par_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_par_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_par_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_par_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_par_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_par_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_par_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_par_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_par_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_par_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_par_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_par_o[0]}]
set_property PACKAGE_PIN T16 [get_ports i_rst]
set_property PACKAGE_PIN U12 [get_ports {i_par_i[7]}]
set_property PACKAGE_PIN T12 [get_ports {i_par_i[6]}]
set_property PACKAGE_PIN Y14 [get_ports {i_par_i[5]}]
set_property PACKAGE_PIN W14 [get_ports {i_par_i[4]}]
set_property PACKAGE_PIN T10 [get_ports {i_par_i[3]}]
set_property PACKAGE_PIN T11 [get_ports {i_par_i[2]}]
set_property PACKAGE_PIN K19 [get_ports {i_par_i[1]}]
set_property PACKAGE_PIN Y16 [get_ports {i_par_i[0]}]
set_property PACKAGE_PIN V18 [get_ports {o_par_o[7]}]
set_property PACKAGE_PIN V17 [get_ports {o_par_o[6]}]
set_property PACKAGE_PIN U15 [get_ports {o_par_o[5]}]
set_property PACKAGE_PIN U14 [get_ports {o_par_o[4]}]
set_property PACKAGE_PIN R14 [get_ports {o_par_o[3]}]
set_property PACKAGE_PIN P14 [get_ports {o_par_o[2]}]
set_property PACKAGE_PIN M15 [get_ports {o_par_o[1]}]
set_property PACKAGE_PIN M14 [get_ports {o_par_o[0]}]

set_false_path -from [get_ports {i_par_i[*]}]
set_false_path -from [get_ports i_rst]
set_input_delay -clock i_clk 0.000 [get_ports {i_par_i[*]}]
set_input_delay -clock i_clk 0.000 [get_ports i_rst]

set_false_path -to [get_ports {o_par_o[*]}]
set_output_delay -clock i_clk 0.000 [get_ports {o_par_o[*]}]

set_property IOSTANDARD LVCMOS33 [get_ports i_rx_line]
set_property IOSTANDARD LVCMOS33 [get_ports o_tx_line]
set_property PACKAGE_PIN Y17 [get_ports i_rx_line]
set_property PACKAGE_PIN T17 [get_ports o_tx_line]

set_property IOSTANDARD LVCMOS33 [get_ports o_i2c_scl]
set_property IOSTANDARD LVCMOS33 [get_ports o_i2c_sda]
set_property PACKAGE_PIN V13 [get_ports o_i2c_scl]
set_property PACKAGE_PIN U17 [get_ports o_i2c_sda]
