# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/andre/Documents/Processor/SOC_GR0040/SOC_GR0040_REFACTOR/SOC_GR0040_REFACTOR.srcs/sources_1/ip/BRAM_8_512_L_1/BRAM_8_512_L.xci
# IP: The module: 'BRAM_8_512_L' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/andre/Documents/Processor/SOC_GR0040/SOC_GR0040_REFACTOR/SOC_GR0040_REFACTOR.gen/sources_1/ip/BRAM_8_512_L_1/BRAM_8_512_L_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_8_512_L'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/andre/Documents/Processor/SOC_GR0040/SOC_GR0040_REFACTOR/SOC_GR0040_REFACTOR.srcs/sources_1/ip/BRAM_8_512_L_1/BRAM_8_512_L.xci
# IP: The module: 'BRAM_8_512_L' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/andre/Documents/Processor/SOC_GR0040/SOC_GR0040_REFACTOR/SOC_GR0040_REFACTOR.gen/sources_1/ip/BRAM_8_512_L_1/BRAM_8_512_L_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_8_512_L'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
