# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Pin_configuration.xdc

# IP: ip/BRAM_8_512_H_1/BRAM_8_512_H.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BRAM_8_512_H || ORIG_REF_NAME==BRAM_8_512_H} -quiet] -quiet
